# Nombre del proyecto
spring.application.name=crudProductos

# Conexión con PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/db_Productos
spring.datasource.username=user_java
spring.datasource.password=0000
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Puerto del proyecto
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false